<!-- Content Header (Page header) -->
<?php echo $this->page()->header("Lista de pontos") ?>



<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <!-- Botão voltar -->
                <button type="button" class="btn btn-default btn-voltar"><i class="fa fa-mail-reply"></i> Voltar</button>
                &nbsp;
                <!-- Botão novo -->
                <button type="button" class="btn btn-primary grid-act-new"> Novo</button>
            </div>
            <div class="ibox-content">
                
                <!-- Grid -->
                <?php echo $this->grid->html(); ?>
            </div>
        </div>
    </div>
</div>




<!-- Right side column. Contains the navbar and content of the page -->
<aside class="right-side">

    

    <!-- Main content -->
    <section class="content">
        <!-- Notificações -->
        <div id="dv-notification"></div>

        <div class="row">
            <div class="col-xs-12">
                <!-- Botão voltar -->
                
                <br /><br />
            </div>
            
            <div class="col-xs-12">

                

            </div>
        </div>
    </section>
</aside>