<!-- Content Header (Page header) -->
<?php echo $this->page()->header("Cadastro de campanhas") ?>


<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Formulário <small>Preencha todos os campos obrigatórios</small></h5>
            </div>
            <div class="ibox-content">
                <?php
                    $this->form->render();
                ?>
            </div>
        </div>
    </div>
</div>

<script>
    var ambientesId = null;
    var agenciaId = null
    <?php
        if( isset($this->registro['ambientes']) ) {
            echo "ambientesId = '" .implode(",", $this->registro['ambientes']) . "'\n";
            echo "ambientesId = ambientesId.split(',');\n";
        }
        if( isset($this->registro['id_empresa_agencia']) ) {
            echo "agenciaId = {$this->registro['id_empresa_agencia']}\n";
        }
    ?>
        
    $(function() {
        
        //Preenche a combo de ambientes
        $("select[name='canais[]']").on("change", function() {
            var canaisId = $("select[name='canais[]']").val();
            $("select[name='ambientes[]']").html("");
            if( canaisId.length ) {
                var canaisIdStr = canaisId.join(",");
                var options = "";
                $.get("/ambiente/list-json", {filter:"id_canal IN ("+canaisIdStr+")"}, function(ambientes) {
                    for( i in ambientes ) {
                        options += "<option value='"+ambientes[i].id+"'>"+ambientes[i].nome+"</option>";
                    }
                    $("select[name='ambientes[]']").html(options);
                    $("select[name='ambientes[]']").trigger("chosen:updated");

                    //Seta os ambientes já salvos
                    for( i in ambientesId ) {
                        var ambienteId = ambientesId[i];
                        $("select[name='ambientes[]'] option[value="+ambienteId+"]").prop("selected", true);
                        $("select[name='ambientes[]']").trigger("chosen:updated");
                    }
                }, 'json');
            } else {
                $("select[name='ambientes[]']").chosen("destroy");
                $("select[name='ambientes[]']").chosen();
            }
        });
        $("select[name='canais[]']").trigger("change");
    
    
        //Preenche a combo de agências
        $("select[name='_id_empresa_cliente']").on("change", function() {
            var $comboAgencia =  $("select[name='_id_empresa_agencia']");
            var empresaId = $(this).val();
            $comboAgencia.html("");
            $comboAgencia.trigger("chosen:updated");
            if( empresaId == SELECT_VALUE_NULL ) {
                return false;
            }
            var options = "<option value='"+SELECT_VALUE_NULL+"'>[Selecione]</option>";
            $.post("/empresa/agencias-por-cliente", {id_empresa_cliente: empresaId}, function(rs) {
                var agencias = getResponse(rs);
                for( i in agencias ) {
                    options += "<option value='"+agencias[i].id+"'>"+agencias[i].nome_comercial+"</option>";
                }
                $comboAgencia.html(options);
                $comboAgencia.trigger("chosen:updated");
                    
                //A agência já cadastrada
                if( agenciaId ) {
                    $comboAgencia.find("option[value="+agenciaId+"]").prop("selected", true);;
                    $comboAgencia.trigger("chosen:updated");
                }
            }, 'json');
            
        });
        $("select[name='_id_empresa_cliente']").trigger("change");

    });
</script>