<!-- Content Header (Page header) -->
<?php echo $this->page()->header("Lista de empresas") ?>

<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <!-- Botão voltar -->
                <button type="button" class="btn btn-default btn-voltar"><i class="fa fa-mail-reply"></i> Voltar</button>
                &nbsp;
            </div>
            <div class="ibox-content">
                
                <!-- Grid -->
                <table class="table tb-campanhas">
                    <thead>
                        <th>Id</th>
                        <th>Nome</th>
                        <th>Início</th>
                        <th>Fim</th>
                        <th>PI</th>
                        <th></th>
                    </thead>
                    <tbody>
                        <?php
                            foreach( $this->campanhas as $campanha ) {
                                echo "<tr>";
                                echo "<td>{$campanha['id']}</td>";
                                echo "<td>{$campanha['campanha']}</td>";
                                echo "<td>{$campanha['inicio']}</td>";
                                echo "<td>{$campanha['fim']}</td>";
                                echo "<td>{$campanha['pi']}</td>";
                                echo "<td><button class='btn btn-primary btn-importar'>Importar</button></td>";
                                echo "</tr>";
                            }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    var auto = false;
    <?php
        if( isset($_GET['auto']) ) {
            echo "auto = true;\n";
        }
    ?>

    //Inicia o processo de importação
    $("table.tb-campanhas button.btn-importar").on("click", function(e) {
        e.preventDefault();
        var $tr = $(this).closest("tr");
        importar($tr);
    });
    function importar($tr, popup) {
        var dados = {
            'importacao' : {
                'id'        : $tr.find('td').eq(0).html(),
                'nome'      : $tr.find('td').eq(1).html(),
                'inicio'    : $tr.find('td').eq(2).html(),
                'fim'       : $tr.find('td').eq(3).html(),
                'pi'        : $tr.find('td').eq(4).html()
            }
        };
        window.location = "/campanha/cadastrar?" + $.param(dados);
    }
</script>