
<!-- Right side column. Contains the navbar and content of the page -->
<aside class="right-side">

    <!-- Content Header (Page header) -->
    <?php echo $this->page()->header() ?>

    <!-- Main content -->
    <section class="content">
        <!-- Notificações -->
        <div id="dv-notification"></div>

        <div class="row">
            <div class="col-xs-12">
                <!-- Botão voltar -->
                <button type="button" class="btn btn-default btn-voltar"><i class="fa fa-mail-reply"></i> Voltar</button>
                <!-- Botão novo -->
                <button type="button" class="btn btn-primary grid-act-new" ajax="true"> Novo</button>
                <br /><br />
            </div>
            
            <div class="col-xs-12">

                <!-- Grid -->
                <?php echo $this->grid->html(); ?>

            </div>
        </div>
    </section>
</aside>