<div>
    <div>

        <h1 class="logo-name">PLUX!</h1>

    </div>
    <h3>Login</h3>
    <form class="m-t" role="form" method="post" action="/usuario/autenticar">
        
        <!-- Usuário -->
        <div class="form-group">
            <input name="usuario" type="text" class="form-control" placeholder="Usuário" required="true">
        </div>
        
        <!-- Senha -->
        <div class="form-group">
            <input name="senha" type="password" class="form-control" placeholder="Senha" required="true">
        </div>
        <button type="submit" class="btn btn-primary block full-width m-b">Entrar</button>

        <p class="text-muted text-center"><a href="#">Esqueceu a senha?</a></p>
    </form>
    <p class="m-t"> <small>Inspinia - Bootstrap 3 &copy; 2014</small> </p>
</div>