<?php
    //Atributos
    $label      = $this->comboConfig['label'];
    $name       = $this->comboConfig['name'];
    $class      = $this->comboConfig['class'];
    $pk         = $this->comboConfig['pk'];
    $firstNull  = $this->comboConfig['firstNull'];
    $entity      = $this->comboConfig['entity'];
    $value      = @$this->comboConfig['value'];
    $required   = ( isset($this->comboConfig['required']) ) ? 'required' : '';
    $multiple   = ( isset($this->comboConfig['multiple']) ) ? 'multiple' : '';
    $placeholder   = ( isset($this->comboConfig['data-placeholder']) ) ? $this->comboConfig['data-placeholder'] : '';
    $rulesArr   = ( isset($this->comboConfig['rules']) ) ? $this->comboConfig['rules'] : array();
    $rules = "";
    if( $required ) {
        $rules = "data-rule-select-not-null='true'";
    }
    foreach( $rulesArr as $ruleAttr => $rule ) {
        if( $rules ) {
            $rules .= " ";
        }
        $rules .= $ruleAttr . "='$rule'";
    }
    
    //Imprime o Html
    echo "<select name='{$name}' id='combo-{$name}' class='{$class}' {$required} "
    . "data-placeholder='{$placeholder}' entity='{$entity}' $rules {$multiple}>";
    
    //Primeiro elemento
    if( $firstNull ) {
        echo '<option value="'.SELECT_VALUE_NULL.'">[Selecione]</option>';
    }
    
    //Lista de valores
    foreach( $this->comboConfig['data'] as $data ) {
        if( !is_array($value) ) {
            $selected = ($data[$pk] == $value) ? 'selected' : '';
        } else {
            $selected = ( in_array($data[$pk], $value) !== FALSE) ? 'selected' : '';
        }
        echo "<option value='{$data[$pk]}' {$selected}>{$data[$label]}</option>";
    }
    echo "</select>";
?>