<div class="col-lg-4">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Contatos</h5>
            <div class="ibox-tools">
                <a title="Novo">
                    <i class="fa fa-plus"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content">

            <table class="table">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Contato</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <!--<tr>
                        <td>Flávio Silva</td>
                        <td>fsilva@mikro.com</td>
                        <td>
                            <a href="" title="Editar"><i class="fa fa-edit"></i></a>&nbsp;
                            <a href="" title="Excluir"><i class="fa fa-remove"></i></a>
                        </td>
                    </tr>-->
                </tbody>
            </table>
            
        </div>
    </div>
</div>

<!-- Modal 
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal2">
    FlipInY effect
</button>-->
<div class="modal inmodal" id="myModal2" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated flipInY">
            <form action="/contato/salvar" method="post" class="form-horizontal">
            
                <!-- Título do Modal -->
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title">Contatos</h4>
                </div>

                <!-- Formulário do Modal -->
                <div class="modal-body">
                    
                    <!-- Nome -->
                    <div class="form-group">
                        <label for="contato-nome" class="col-sm-2 control-label">* Nome</label>
                        <div class="col-sm-10">
                            <input required="1" autofocus="1" type="text" class="form-control" name="nome">
                        </div>
                    </div>
                    
                    <!-- Tipo -->
                    <div class="form-group">
                        <label for="combo-tipo" class="col-sm-2 control-label">* Tipo</label>
                        <div class="col-sm-10">
                            <?php echo $this->Component()->comboConstant('CONTATO_TIPO', "tipo"); ?>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>
