<?php
    $lstMenu = array(
        array('nome' => 'Resumo','icone' => 'fa fa-table','link' => '/default/index/index'),
        array('nome' => 'Segurança','icone' => 'fa fa-lock','link' => '/default/index/seguranca', 'sub' => array(
            array('link' => '/usuario', 'nome' => 'Usuários'),
        )),
    );
    
    //Carrega os menus
    function loadMenu( $lstMenu ) {
        
        foreach( $lstMenu as $menu ) {
            
            //Checa o acesso
            if( isset($menu['link']) ) {
                $autorizado = Core_Seguranca::check($menu['link'], Core_Seguranca::getUser()->idPerfil);
            } else {
                $menu['link'] = '';
                $autorizado = true;
            }
            
            //Exibe o menu
            if( $autorizado ) {
                $class = ( isset($menu['sub']) ) ? 'treeview' : '';
                $class .= ( $_SERVER['REQUEST_URI'] == $menu['link'] ) ? ' active' : '';
                
                if( !isset($menu['icone']) ) {
                    $menu['icone'] = '';
                }
                
                echo "  <li class='{$class}'>
                            <a href='{$menu['link']}'>
                                <i class='{$menu['icone']}'></i>
                                <span class='nav-label'>{$menu['nome']}</span>";
                if( isset($menu['sub']) ) {
                    echo ' <span class="fa arrow">';
                }
                                    
                echo "</a>";
                        
                //Submenu
                if( isset($menu['sub']) ) {
                    echo "  <ul class='nav nav-second-level'>";
                    loadMenu($menu['sub']);
                    echo "  </ul>";
                }
                                
                echo "  </li>";
            }
        }
        
    }
?>
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            
            <!-- Perfil -->
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="" class="dropdown-toggle" href="javascript:void(0)">
                        <span class="clear"> 
                            <span class="block m-t-xs"> 
                                <strong class="font-bold"><?php echo Core_Seguranca::getUser()->nome . " " . Core_Seguranca::getUser()->sobrenome ?></strong>
                            </span> 
                            <span class="text-muted text-xs block"><?php echo Core_Seguranca::getUser()->perfil ?></span> 
                        </span> 
                    </a>
                </div>
                <div class="logo-element">
                    IN+
                </div>
            </li>
            
            <!-- Opções -->
            <?php loadMenu($lstMenu); ?>

        </ul>
    </div>
</nav>
