<?php
    //Recupera os menus
    $menuItens = $this->mainMenu->getItens();
    
    //Carrega os menus
    function loadMenu( $menuItens ) {
        
        foreach( $menuItens as $item ) {
            
            //Checa o acesso
            if( isset($item->link) ) {
                $autorizado = Core_Seguranca::check($item->link, Core_Seguranca::getUser()->idPerfil);
            } else {
                $item->link = '';
                $autorizado = true;
            }
            
            //Exibe o menu
            if( $autorizado ) {
                $class = "";
                if( $item->isActive() ) {
                    $class = "active";
                }
                
                //Ícone
                if( !isset($item->icone) ) {
                    $item->icone = '';
                }
                
                //ul li
                echo "  <li class='{$class}'>
                            <a href='{$item->action}'>
                                <i class='{$item->icon}'></i>
                                <span class='nav-label'>{$item->name}</span>";
                if( isset($item->sub) ) {
                    echo ' <span class="fa arrow">';
                }
                                    
                echo "</a>";
                        
                //Submenu
                if( count($item->getSubitens()) ) {
                    echo "  <ul class='nav nav-second-level'>";
                    loadMenu($item->getSubitens());
                    echo "  </ul>";
                }
                                
                echo "  </li>";
            }
        }
        
    }
?>
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            
            <!-- Perfil -->
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="" class="dropdown-toggle" href="javascript:void(0)">
                        <span class="clear"> 
                            <span class="block m-t-xs"> 
                                <strong class="font-bold"><?php echo Core_Seguranca::getUser()->nome . " " . Core_Seguranca::getUser()->sobrenome ?></strong>
                            </span> 
                            <span class="text-muted text-xs block"><?php echo Core_Seguranca::getUser()->perfil ?></span> 
                        </span> 
                    </a>
                </div>
                <div class="logo-element">
                    IN+
                </div>
            </li>
            
            <!-- Opções -->
            <?php loadMenu($menuItens); ?>

        </ul>
    </div>
</nav>
