<?php
    $lstMenu = array(
        array('nome' => 'Resumo','icone' => 'fa fa-table','link' => '/default/index/index'),
        array('nome' => 'Configurações','icone' => 'fa fa-gears','link' => '/default/index/config', 'sub' => array(
            array('link' => '/usuario', 'nome' => 'Usuários', 'icone'=>'fa fa-angle-double-right'),
        )),
    );
    
    //Carrega os menus
    function loadMenu( $lstMenu ) {
        
        foreach( $lstMenu as $menu ) {
            
            //Checa o acesso
            if( isset($menu['link']) ) {
                $autorizado = Core_Seguranca::check($menu['link'], Core_Seguranca::getUser()->idPerfil);
            } else {
                $menu['link'] = '';
                $autorizado = true;
            }
            
            if( $autorizado ) {
                $class = ( isset($menu['sub']) ) ? 'treeview' : '';
                $class .= ( $_SERVER['REQUEST_URI'] == $menu['link'] ) ? ' active' : '';
                
                //Imprime
                if( !isset($menu['icone']) ) {
                    $menu['icone'] = '';
                }
                echo "  <li class='{$class}'>
                            <a href='{$menu['link']}'>
                                <i class='{$menu['icone']}'></i>
                                <span>{$menu['nome']}</span>
                            </a>";
                        
                //Submenu
                if( isset($menu['sub']) ) {
                    echo "  <ul class='treeview-menu'>";
                    loadMenu($menu['sub']);
                    echo "  </ul>";
                }
                                
                echo "  </li>";
            }
        }
        
    }
?>

<aside class="left-side sidebar-offcanvas">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div id="logo-cliente"></div>
        <div class="user-panel">
            <div class="pull-left info">
                <p>Olá, <?php echo Core_Seguranca::getUser()->nome ?></p>
                  <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <?php loadMenu($lstMenu); ?>
        </ul>

    </section>
    <!-- /.sidebar -->
</aside>


