<!-- Content Header (Page header) -->
<?php echo $this->page()->header("Lista de bookings") ?>

<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <!-- Botão voltar -->
                <button type="button" class="btn btn-default btn-voltar"><i class="fa fa-mail-reply"></i> Voltar</button>
                &nbsp;
                <!-- Botão novo -->
                <button type="button" class="btn btn-primary grid-act-new"> Novo</button>
            </div>
            <div class="ibox-content">
                
                <!-- Grid -->
                <?php echo $this->grid->html(); ?>
            </div>
        </div>
    </div>
</div>

<script>
    $(function() {
        
        //Redireciona para a tela de importação
        $("button#btn-importar").on("click", function(e) {
            e.preventDefault();
            window.location = "/campanha/importar";
        });
    });
</script>