<!-- STEP PHOTOS -->
<div class="tab-booking animated fadeInRight" id="tab-step-form">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Formulário <small>Preencha todos os campos obrigatórios</small></h5>
                </div>
                <div class="ibox-content form-horizontal">
                    <form id="form-booking" action="" method="post" class="form-horizontal">
                        
                        <!-- id -->
                        <?php
                            if( isset($this->registro['id']) ) {
                                echo "<input type='hidden' name='id' value='{$this->registro['id']}' />";
                            }
                        ?>
                        
                        <!-- Campanha -->
                        <div class="form-group">
                            <label for="" class="col-sm-2 control-label">* Campanha</label>
                            <div class="col-sm-10">
                                <?php echo $this->Component()->combo("campanha", 
                                        array("required"=>true, "name"=>"id_campanha")); ?>
                                <label id="combo-id_campanha-error" class="error" for="combo-id_campanha"></label>
                            </div>
                        </div>
                        
                        <!-- Tipo de Booking -->
                        <div class="form-group">
                            <label for="" class="col-sm-2 control-label">* Tipo de Booking</label>
                            <div class="col-sm-10">
                                <select class="form-control chosen-select" name="tipo" required="true">
                                    <option value="BOOKING_COMPLETO">Completo</option>
                                    <option value="BOOKING_AMOSTRAGEM">Amostragem</option>
                                </select>
                            </div>
                        </div>
                        
                        <!-- Canais -->
                        <div class="form-group">
                            <label for="" class="col-sm-2 control-label">* Canais</label>
                            <div class="col-sm-10">
                                <?php echo $this->Component()->combo(null, array("multiple"=>true, 
                                    "name"=>"canais[]", "required"=>true)); ?>
                                <label id="combo-canais[]-error" class="error" for="combo-canais[]"></label>
                            </div>
                        </div>
                                         
                        <!-- Layout -->
                        <div class="form-group">
                            <label for="" class="col-sm-2 control-label">Layout</label>
                            <div class="col-sm-10">
                                <?php echo $this->Component()->comboConstant('BOOKING_LAYOUT', "layout", array("firstNull"=>false,
                                    "value"=>@$this->registro['layout'])); ?>
                            </div>
                        </div>
                                         
                        <!-- Assinatura -->
                        <?php
                            if( isset($this->registro['assinatura']) ) {
                                $assinatura = $this->registro['assinatura'];
                            } else {
                                $assinatura = "OPEC: Samuel Ferreira de Andrade _ CPF: 032.042.821-47 _ RG: 2.799.371 - SSP/DF";
                            }
                        ?>
                        <div class="form-group">
                            <label for="" class="col-sm-2 control-label">Assinatura</label>
                            <div class="col-sm-10">
                                <input type="text" name="assinatura" class="form-control" value="<?php echo $assinatura ?>" />
                            </div>
                        </div>

                    </form>
                    <?php echo $this->render("booking/step-buttons.phtml"); ?>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    var canaisSelecionados = new Array();
    
    $(function() {
        <?php
            if( isset($this->registro) ) {
                
                //Preenche o campo de campanha
                echo "$('[name=id_campanha]').val({$this->registro['id_campanha']});\n";
                echo "$('[name=id_campanha]').trigger('chosen:updated');\n";
                echo "$('[name=id_campanha]').trigger('change');\n";
                
                //Canais
                if( $this->registro['canais'] ) {
                    foreach( $this->registro['canais'] as $canal ) {
                        echo "canaisSelecionados.push({$canal});\n";
                    }
                }
                
                //Preenche o campo de layout
                echo "$('[name=layout]').val({$this->registro['layout']});\n";
                echo "$('[name=layout]').trigger('chosen:updated');\n";
                
                //Fotos
                if( isset($this->registro['fotos']) && $this->registro['fotos'] ) {
                    echo "listaFotos = JSON.parse('{$this->registro['fotos']}');\n";
                }
            }
        ?>
    });
    
    //Configurações default
    Form.init("form-booking");    
        
    var agenciaId = null
    
    //Carrega os canais de acordo com a campanha selecionada
    var $comboCampanha = $("select[name='id_campanha']");
    var $comboCanal =  $("select[name='canais[]']");
    Form.callback = function() {
        if( canaisSelecionados ) {
            for( i in canaisSelecionados ) {
                $comboCanal.find("option[value=" + canaisSelecionados[i] + "]").prop("selected", true);
                $comboCanal.trigger('chosen:updated');
                canaisSelecionados = new Array();
            }
        }
    }
    Form.filterCombo($comboCanal, $comboCampanha, "/campanha/canais-por-campanha");
        
    //Submete o formulário
    $("button.btn-next").off("click");
    $("button.btn-next").on("click", function() {
        $("form#form-booking").submit();    
    });
    $("form#form-booking").on("submit", function(e) {
        if( $("#form-booking").valid() ) {
            $btnStep = $("div.booking-steps button.btn-success");
            var step = $btnStep.parent().index() + 1;
            $.getJSON("/booking/manter-em-sessao?"+$(this).serialize(), function(rs) {
                var resp = getResponse(rs);
                toStep(step);
            });
            
            return false;
        }
    });

</script>