<!-- STEP PHOTOS -->
<div class="tab-booking form-horizontal animated fadeInRight" id="tab-step-photos" style="display:none">
    <div class="row">
        <div class="col-lg-3">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <form id="form-booking-fotos">
                        <div class="file-manager">
                            <h5>Resumo</h5>
                            <div id="resumoSelecionadas">Fotos selecionadas: <strong>0</strong></div>
                            <div id="resumoPendencias">Pendências: <strong>0</strong></div>
                            <div class="hr-line-dashed"></div>
                            
                            <h5>Período</h5>
                            <div>
                                <!--<label>Período</label> -->
                                <div class="row">
                                    <div class="col-md-6"><input type="text" class="form-control datepicker" name="dt_inicio" placeholder="Início"></div>
                                    <div class="col-md-6"><input type="text" class="form-control datepicker" name="dt_fim" placeholder="Fim"></div>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            
                            <!-- Ambientes -->
                            <div id="dvFiltroAmbientes" style="display:none">
                                <h5>Ambientes</h5>
                                <div id="jstree1"></div>

                                <div class="hr-line-dashed"></div>
                            </div>
                            
                            <button class="btn btn-primary btn-block" id="btnCarregarFotos">Carregar fotos</button>
                            <div class="clearfix"></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- Galeria -->
        <div class="col-lg-9">
            <div class="ibox float-e-margins" id="ibox-galeria">
                <div class="ibox-content">
                    <?php 
                        $this->lineButtons = false;
                        echo $this->render("booking/step-buttons.phtml"); 
                    ?>
                    <div class="sk-spinner sk-spinner-wave">
                        <div class="sk-rect1"></div>
                        <div class="sk-rect2"></div>
                        <div class="sk-rect3"></div>
                        <div class="sk-rect4"></div>
                        <div class="sk-rect5"></div>
                    </div>
                    
                    <div class="row">
                        <div class="col-lg-12">
                            <!--<div class="grid-options" style="display: none">
                                <button class="btn btn-default btn-select-all">Selecionar todas</button>
                                <button class="btn btn-default btn-deselect-all">Deselecionar todas</button>
                                <button class="btn btn-default btn-select-interval">Selecionar intervalo</button>
                            </div>-->
                            <div class="hr-line-dashed"></div>
                            <p id="msg-sem-img"></p>
                            <div id="container-booking-imagens"></div>
                        </div>
                    </div>
                    <div class="booking-pagination">
                    </div>
                    <?php 
                        $this->lineButtons = true;
                        echo $this->render("booking/step-buttons.phtml"); 
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>

<?php $this->headLink()->appendStylesheet($this->baseUrl() . '/resources/jsTree/style.min.css'); ?>
<?php $this->inlineScript()->appendFile($this->baseUrl() . '/resources/jsTree/jstree.min.js'); ?>
<?php $this->inlineScript()->appendFile($this->baseUrl() . '/js/pagination.js'); ?>
<script>
    var pagination;
    var currentPage;
    Form.init("form-booking-fotos");
    
    //Seleciona todas as imagens
    $("div.grid-options button.btn-select-all").on('click', function(e) {
        e.preventDefault();
        $("div.file-box div.file").each(function() {
            selecionarFoto($(this));
        });
    })
    
    //Deseleciona todas as imagens
    $("div.grid-options button.btn-deselect-all").on('click', function(e) {
        e.preventDefault();
        $("div.file-box div.file").each(function() {
            deselecionarFoto($(this));
        });
    })
    
    //Seleciona o intervalo
    $("div.grid-options button.btn-select-interval").on('click', function(e) {
        e.preventDefault();
        if( !selecionarIntervalo() ) {
            $(this).addClass('btn-primary');
            $(this).removeClass('btn-default');
        } else {
            $(this).removeClass('btn-primary');
            $(this).addClass('btn-default');
        }
    });
    function selecionarIntervalo() {
        return $("div.grid-options button.btn-select-interval").hasClass('btn-primary');
    }
    
    //Preenche a combo Ambiente
    var treeViewExists = false;
    function stepPhotosInit() {
        
        //Limpa os campos
        $("#dvFiltroAmbientes").hide();
        hideGrid();
    }
    
    //Recupera o item selecionado
    function getAmbienteSelecionado() {
        var ambienteId = null;
        var itens = $('#jstree1').jstree('get_selected');
        if( itens.length > 0 && typeof(itens[0]) != 'object' ) {
            ambienteId = itens[0];
        }
        return ambienteId;
    }
    
    //Carrega as fotos
    $("#btnCarregarFotos").on("click", function(e) {
        e.preventDefault();
        var $dataInicio = $("#form-booking-fotos input[name=dt_inicio]");
        var $dataFim = $("#form-booking-fotos input[name=dt_fim]");
        var $canais = $("select[name='canais[]']");
        var formValid = true;
        var ambienteId = getAmbienteSelecionado();
        $.each([$dataInicio, $dataFim], function(idx, $campo) {
            if( $campo.val() == '' ) {
                $campo.addClass("error");
                formValid = false;
            } else {
                $campo.removeClass("error");
            }
        })
        if( !formValid ) {
            return false;
        }
   
        //Carrega as fotos
        carregarFotos($canais.val(), $dataInicio.val(), $dataFim.val(), 1, true);
        
    });
    
    //Evento de clique na página
    $(".booking-pagination").on("click", "li.paginate_button a", function(e) {
        e.preventDefault();
        
        //Seleciona a página
        var page = null;
        var liParent = $(this).closest("li");
        if( liParent.hasClass('previous') ) {
            page = parseInt(liParent.parent().find('li.active a').html()) - 1;
            if( page <= 0 ) {
                return;
            }
        } else if( liParent.hasClass('next') ) {
            page = parseInt(liParent.parent().find('li.active a').html()) + 1;
            if( page > pagination.totalPages ) {
                return;
            }
        } else {
            page = $(this).html();
        }
        
        //Recarrega as fotos
        var $dataInicio = $("#form-booking-fotos input[name=dt_inicio]");
        var $dataFim = $("#form-booking-fotos input[name=dt_fim]");
        var $canais = $("select[name='canais[]']");
        var ambienteId = getAmbienteSelecionado();
        carregarFotos($canais.val(), $dataInicio.val(), $dataFim.val(), page, false, ambienteId);
        
        //On top
        window.scrollTo(0, 0);
    })
    
    //Evento de clique na foto
    var listaFotos = new Array();
    var click1 = null;
    var click2 = null;
    $("#container-booking-imagens").on("click", "div.file", function(e) {
        e.preventDefault();
        var key = $(this).attr('key');
        var index = listaFotos.indexOf(key);
        if( !$(this).hasClass("selected") ) {
            selecionarFoto($(this));
        } else {
            deselecionarFoto($(this));
        }
    });
    
    //Atualiza o contador
    function atualizarContador() {
        var total = listaFotos.length;
        $("#resumoSelecionadas strong").html(total);
    }
    
    //Seleciona a foto
    function selecionarFoto($item, semIntervalo) {
        var key = $item.attr('key');
        var index = listaFotos.indexOf(key);
        $item.addClass("selected");
        if( index == -1 ) {
            listaFotos.push(key);
        }
        
        //Seleção de intervalo
        if( selecionarIntervalo() && !semIntervalo ) {
            var files = $("div.file-box div.file");
            if( !click1 ) {
                click1 = $item;
            } else {
                click2 = $item;
                var indice1 = recuperarIndice(click1), indice2 = recuperarIndice(click2);
                var start = indice1, end = indice2;
                if( indice2 < indice1 ) {
                    start = indice2;
                    end = indice1;
                }
                click1 = null;
                click2 = null;
                for( var i = (start+1); i < end; i++ ) {
                    selecionarFoto(files.eq(i), true);
                }
            }
        }
        atualizarContador();
    }
    
    //Recupera o indice da imagem
    function recuperarIndice($item) {
        var files = $("div.file-box div.file");
        if( files.length ) {
            for( var i = 0; i < files.length; i++ ) {
                if( files.eq(i).attr('key') == $item.attr('key') ) {
                    return i;
                }
            }
        }
        return null;
    }
    
    //Deseleciona a foto
    function deselecionarFoto($item) {
        var key = $item.attr('key');
        var index = listaFotos.indexOf(key);
        $item.removeClass("selected");
        if( index > -1 ) {
            listaFotos.splice(index, 1);
        }
        atualizarContador();
    }
    
    //Carrega as fotos
    function carregarFotos(canais, dataInicio, dataFim, pagina, atualizarTreeview, ambienteId) {
        click1 = null;
        currentPage = pagina;
        $('#ibox-galeria').children('.ibox-content').toggleClass('sk-loading');
        
        //Realiza a requisição
        var filtros = {
            data_inicio: dataInicio,
            data_fim: dataFim,
            pagina: pagina,
            canais: canais,
            campanha_id: $("select[name=id_campanha]").val()
        }
        if( ambienteId ) {
            filtros.ambiente_id = ambienteId;
        }
        $.get("/booking/carregar-imagens?"+jQuery.param(filtros), function(rs) {
            var dados = getResponse(rs);
            var imagens = dados.indices;
            var canais = dados.canais;
            if( imagens ) {
                if( imagens && imagens.length ) {
                    showGrid();
                } else {
                    $("#msg-sem-img").html("Não foram encontradas imagens");
                    hideGrid();
                }
                var html = "";
                for( i in imagens ) {
                    if( i == 0 ) {
                        html += "<div>";
                    } else if( i % 4 == 0 ) {
                        //html += "<div style='clear:both'></div></div>";
                        html += "<div>";
                    }
                    var key = imagens[i].key;
                    var selected = "";
                    if( listaFotos.indexOf(key) > -1 ) {
                        selected = "selected";
                    }
                    var nmAmbiente = imagens[i].ambiente;
                    if( nmAmbiente.length > 45 ) {
                        nmAmbiente = imagens[i].ambiente.substr(0, 45) + "...";
                    }
                    
                    html += "\n\
                        <div class='file-box'>\n\
                            <div class='file "+selected+"' key='"+imagens[i].key+"'>\n\
                                <div class='correct'><img src='/img/correct.png' /></div>\n\
                                <div class='over'></div>\n\
                                <a href='#'>\n\
                                    <div class='image'>\n\
                                        <img alt='image' class='img-responsive' src='"+imagens[i].url+"'>\n\
                                    </div>\n\
                                    <div class='file-name'>\n\
                                        " + nmAmbiente + "\n\
                                        <br/>\n\
                                        <small><strong>Tela: " + imagens[i].tela + "</strong> - " + imagens[i].data_foto + "</small>\n\
                                    </div>\n\
                                </a>\n\
                            </div>\n\
                        </div>";
                }
                html += "</div>";
                $('#ibox-galeria').children('.ibox-content').toggleClass('sk-loading');
                $("#container-booking-imagens").html(html);
                
                //Gera a paginação
                pagination = new Pagination(dados.total, dados.limite, pagina);
                var pagHtml = pagination.render();
                $(".booking-pagination").html(pagHtml);
                
                //Carrega a treeview
                if( atualizarTreeview ) {
                    $('#jstree1').jstree('destroy');
                    var data = new Array();
                    for( i in canais ) {
                        if( canais[i].ambientes ) {
                            var canal = {
                                'text' : canais[i].nome
                                //'state' : {'opened' : true}
                            };
                            canal.children = new Array();
                            for( j in canais[i].ambientes ) {
                                canal.children.push({
                                    'id' : canais[i].ambientes[j].id,
                                    'text' : canais[i].ambientes[j].nome + " (" + canais[i].ambientes[j].indices + ")",
                                    'type' : 'ambiente'
                                });
                            }
                            data.push(canal);
                        } else {
                            data.push(canais[i].nome);
                        }
                    }
                    carregarTreeview(data);
                }
            }
        }, 'json');
    }
    
    //Carrega a treeview
    var lastTreeItem = null;
    function carregarTreeview(data) {
        $("#dvFiltroAmbientes").show();
        $('#jstree1').jstree({
            core : {
                data : data
            },
            'plugins' : [ 'types' ],
            'types' : {
                'default' : {'icon' : 'fa fa-folder'},
                'ambiente' : {'icon' : 'none'}
            }
        //}).on('select_node.jstree', function(e, data) {
        }).on('changed.jstree', function(e, data) {
            if( !data.node || data.node.parent == '#' ) {
                return;
            }
            
            var $dataInicio = $("#form-booking-fotos input[name=dt_inicio]");
            var $dataFim = $("#form-booking-fotos input[name=dt_fim]");
            var $canais = $("select[name='canais[]']");
            if( lastTreeItem && lastTreeItem == data.node.id ) {
                $('#jstree1').jstree(true).deselect_all();
                lastTreeItem = null;
                ambienteId = null;
                carregarFotos($canais.val(), $dataInicio.val(), $dataFim.val(), 1, false);
            } else {
                lastTreeItem = data.node.id;
                var ambienteId = data.node.id;
                carregarFotos($canais.val(), $dataInicio.val(), $dataFim.val(), 1, false, ambienteId);
            }
        });
    }
    
    //Exibe oculta a grid
    function showGrid() {
        $("#msg-sem-img").hide();
        $("#container-booking-imagens").show();
        $(".grid-options").show();
        $(".booking-pagination").show();
    }
    function hideGrid() {
        $("#msg-sem-img").show();
        $("#container-booking-imagens").hide();
        $(".grid-options").hide();
        $(".booking-pagination").hide();
    }
    
    //Avança para a tela de exportação
    $("button.btn-next").off("click");
    $("button.btn-next").on("click", function() {
        $("form#form-booking").submit();    
    });
</script>