<?php echo $this->doctype(); ?>

<html lang="pt">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Gestor PLUX!')->setSeparator(' - ')->setAutoEscape(false); ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no')
        ?>

        <!-- CSS -->
        <?php
        $temaSession = new Zend_Session_Namespace("tema");

        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->baseUrl() . '/img/favicon.ico'))
                ->appendStylesheet($this->baseUrl() . '/css/bootstrap/bootstrap.min.css')
                ->appendStylesheet($this->baseUrl() . '/resources/font-awesome-4.3.0/css/font-awesome.min.css')
                //Ionicons
                ->appendStylesheet($this->baseUrl() . '/css/bootstrap/ionicons.min.css')
                //Morris chart
                ->appendStylesheet($this->baseUrl() . '/css/bootstrap/morris/morris.css')
                //jvectormap
                ->appendStylesheet($this->baseUrl() . '/css/bootstrap/jvectormap/jquery-jvectormap-1.2.2.css')
                //bootstrap wysihtml5 - text editor
                ->appendStylesheet($this->baseUrl() . '/css/bootstrap/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')
                //AdminLTE
                ->appendStylesheet($this->baseUrl() . '/css/bootstrap/AdminLTE.css')
                //Combobox
                ->appendStylesheet($this->baseUrl() . '/resources/select2-master/css/select2.min.css')
                ->appendStylesheet($this->baseUrl() . '/resources/select2-master/css/select2-bootstrap.css')
                //Upload
                ->appendStylesheet($this->baseUrl() . '/resources/kartik-v-bootstrap-fileinput-dd9a8de/css/fileinput.min.css')
                //Customizado
                ->appendStylesheet($this->baseUrl() . '/css/style.css?nocache=1')
                //DataTable
                ->appendStylesheet($this->baseUrl() . '/css/bootstrap/datatables/jquery.dataTables.css')
                //Datetimepicker
                ->appendStylesheet($this->baseUrl() . '/resources/datetimepicker/bootstrap-datetimepicker.css')
                //Tema
                ->appendStylesheet($this->baseUrl() . '/css/temas/' . $temaSession->css . '.css');
        ?>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->appendFile($this->baseUrl() . '/js/bootstrap/jquery.min.js')
                ->appendFile($this->baseUrl() . '/js/bootstrap/bootstrap.min.js')
                ->appendFile($this->baseUrl() . '/js/bootstrap/jquery-ui.min.js')
                //Morris
                ->appendFile($this->baseUrl() . '/js/bootstrap/plugins/morris/raphael-min.js')
                ->appendFile($this->baseUrl() . '/js/bootstrap/plugins/morris/morris.min.js')
                //Sparkline
                ->appendFile($this->baseUrl() . '/js/bootstrap/plugins/sparkline/jquery.sparkline.min.js')
                //jvectormap
                ->appendFile($this->baseUrl() . '/js/bootstrap/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js')
                ->appendFile($this->baseUrl() . '/js/bootstrap/plugins/jvectormap/jquery-jvectormap-world-mill-en.js')
                //jQuery Knob Chart
                ->appendFile($this->baseUrl() . '/js/bootstrap/plugins/jqueryKnob/jquery.knob.js')
                //Bootstrap WYSIHTML5
                ->appendFile($this->baseUrl() . '/js/bootstrap/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js')
                //iCheck
                ->appendFile($this->baseUrl() . '/js/bootstrap/plugins/iCheck/icheck.min.js')
                //AdminLTE App
                ->appendFile($this->baseUrl() . '/js/bootstrap/AdminLTE/app.js')
                //Combobox
                ->appendFile($this->baseUrl() . '/resources/select2-master/js/select2.full.min.js')
                //Upload
                ->appendFile($this->baseUrl() . '/resources/kartik-v-bootstrap-fileinput-dd9a8de/js/fileinput.min.js')
                //MaskedInput
                ->appendFile($this->baseUrl() . '/js/jquery.maskedinput.min.js')
                //DataTable
                ->appendFile($this->baseUrl() . '/js/bootstrap/plugins/datatables/jquery.dataTables.js')
                ->appendFile($this->baseUrl() . '/js/bootstrap/plugins/datatables/dataTables.bootstrap.js')
                //Moments
                ->appendFile($this->baseUrl() . '/js/bootstrap/moment-with-locales.js')
                //Datetimepicker
                ->appendFile($this->baseUrl() . '/resources/datetimepicker/bootstrap-datetimepicker.js')
                ->appendFile($this->baseUrl() . '/resources/datetimepicker/pt-br.js')
                //Scripts padrões do sistema
                ->appendFile($this->baseUrl() . '/js/general.js?v=1')
                ->appendFile($this->baseUrl() . '/js/grid.js')
                ->appendFile($this->baseUrl() . '/js/form.js')
                ->appendFile($this->baseUrl() . '/js/jquery.limit-1.2.source.js');
        ?>

    </head>

    <body class="skin-blue">
        <!-- wait block -->
        <div class="modal fade" id="pleaseWaitDialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body">
                        <h4 class="modal-title" align="center">Aguarde...</h4>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
        <!-- block -->
        <div class="modal fade" id="blockWaitDialog"></div>

        <!-- header logo: style can be found in header.less -->
        <header class="header">
            <a href="/" class="logo">
                <!-- Add the class icon to your logo image or logo icon to add the margining -->
                Gestor de Conteúdo
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" role="navigation">

                <?php if (Core_Seguranca::autenticado()): ?>
                    <!-- Botão Menu -->
                    <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>

                    <div class="navbar-right">
                        <ul class="nav navbar-nav">

                            <!-- Notificações -->
                            <li class="dropdown notifications-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-envelope-o"></i>
                                    0
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="header">Você tem 0 notificações não lidas</li>
                                    <li>
                                        <!-- inner menu: contains the actual data -->
                                        <ul class="menu">
                                            
                                        </ul>
                                    </li>
                                    <li class="footer"><a href="/default/notificacao/index">Ver todas</a></li>
                                </ul>
                            </li>

                            <!-- Perfil do usuário conectado -->
                            <li class="dropdown user user-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="glyphicon glyphicon-user"></i>
                                    <span><?php echo Core_Seguranca::getUser()->nome ?> <i class="caret"></i></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <!-- User image -->
                                    <li class="user-header bg-light-blue">
                                        <!--<img src="/img/avatar3.png" class="img-circle" alt="User Image" />-->
                                        <p>
                                            <?php echo Core_Seguranca::getUser()->nome . " " . Core_Seguranca::getUser()->sobrenome ?>
                                            <small>(<?php echo Core_Seguranca::getUser()->perfil ?>)</small>
                                        </p>
                                    </li>
                                    <!-- Menu Footer-->
                                    <li class="user-footer">
                                        <!--<div class="pull-left">
                                            <a href="#" class="btn btn-default btn-flat">Configurações</a>
                                        </div>-->
                                        <div class="pull-right">
                                            <a href="/usuario/sair" class="btn btn-default btn-flat">Sair</a>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                <?php endif; ?>
            </nav>
        </header>

        <div class="wrapper row-offcanvas row-offcanvas-left">

            <!-- Menu -->
            <?php
            if (Core_Seguranca::autenticado()) {
                echo $this->menu()->main();
            }
            ?>

            <!-- Imprime o conteúdo de cada página -->
            <?php echo $this->layout()->content; ?>

        </div><!-- ./wrapper -->

        <?php
        //Carrega as mensagens do sistema
        Core_Notificacao::exibir();

        //Js Inline
        echo $this->InlineScript();
        
        ?>
        <!-- Notificações --->
        <script>
            /*setInterval(function() {
                $.get("/notificacao/existe-msg-desktop", function(rs) {
                    if( rs == 1 ) {
                        showNotificationDesktop("Há novas mensagens para você", "/default/notificacao/index");
                    }
                });
            }, 30000);*/
        </script>

    </body>
</html>
