<?php echo $this->doctype(); ?>

<html lang="pt">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Gestor PLUX!')->setSeparator(' - ')->setAutoEscape(false); ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- CSS -->
        <?php
        echo $this->headLink()
                ->appendStylesheet($this->baseUrl() . '/css/bootstrap.min.css')
                ->appendStylesheet($this->baseUrl() . '/resources/font-awesome/css/font-awesome.css')
                ->appendStylesheet($this->baseUrl() . '/css/animate.css')
                ->appendStylesheet($this->baseUrl() . '/css/style.css')
                //Datepicker
                ->appendStylesheet($this->baseUrl() . '/resources/datepicker/datepicker3.css')
                //Toastr
                ->appendStylesheet($this->baseUrl() . '/resources/toastr/toastr.min.css')
                //Datatable
                ->appendStylesheet($this->baseUrl() . '/resources/datatables/jquery.dataTables.css');
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                
            //Mainly scripts
            ->appendFile($this->baseUrl() . '/js/jquery-3.1.1.min.js')
            ->appendFile($this->baseUrl() . '/js/bootstrap.min.js')
            ->appendFile($this->baseUrl() . '/js/plugins/metisMenu/jquery.metisMenu.js')
            ->appendFile($this->baseUrl() . '/js/plugins/slimscroll/jquery.slimscroll.min.js')
            //Datatable
            ->appendFile($this->baseUrl() . '/resources/datatables/js/jquery.dataTables.js')
            ->appendFile($this->baseUrl() . '/resources/datatables/js/dataTables.bootstrap.js')
            //MaskedInput
            ->appendFile($this->baseUrl() . '/js/plugins/jquery.maskedinput.min.js')
            //Datepicker
            ->appendFile($this->baseUrl() . '/resources/datepicker/bootstrap-datepicker.js')
            ->appendFile($this->baseUrl() . '/resources/datepicker/locales/bootstrap-datepicker.pt.js')
            //Toastr
            ->appendFile($this->baseUrl() . '/resources/toastr/toastr.min.js')
            //Custom and plugin
            ->appendFile($this->baseUrl() . '/js/inspinia.js')
            ->appendFile($this->baseUrl() . '/js/plugins/pace/pace.min.js')
            ->appendFile($this->baseUrl() . '/js/grid.js')
            ->appendFile($this->baseUrl() . '/js/general.js')
            ->appendFile($this->baseUrl() . '/js/form.js');
        ?>

    </head>

    <body>
        <div id="wrapper">
            
            <!-- Menu -->
            <?php echo $this->menu()->main(); ?>
            
            <div id="page-wrapper" class="gray-bg">
                <div class="row border-bottom">
                    <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
                        <div class="navbar-header">
                            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                            <form role="search" class="navbar-form-custom" method="post" action="#">
                                <div class="form-group">
                                    <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
                                </div>
                            </form>
                        </div>
                        <ul class="nav navbar-top-links navbar-right">
                            <li>
                                <a href="/usuario/sair">
                                    <i class="fa fa-sign-out"></i> Sair
                                </a>
                            </li>
                        </ul>

                    </nav>
                </div>
                
                <!-- Conteúdo -->
                <?php echo $this->layout()->content; ?>
                
                <div class="footer">
                    <div class="pull-right">
                    </div>
                    <div>
                        PLUX! - Grupo Diários Associados
                    </div>
                </div>

            </div>
        </div>
        
        <!-- Notificação -->
        <?php
            Core_Notificacao::exibir();
        ?>
    </body>
</html>
